### ISSUE TITLE
Specific pandas version required to read in pickled results

### ISSUE THREAD

**Issue by Emmavt** [dlab-berkeley/Python-Web-APIs#4]
In 02_api.ipynb, we read in the results of an API query about the 2020 election using the following code:
`df = pd.read_pickle("../data/election2020_articles.pkl")`

As per this [issue](https://github.com/pandas-dev/pandas/issues/55137) on the pandas github, the pd.read_pickle function is not backwards compatible, so we will need workshop attendees to have pandas version 1.3.4 (or an earlier version). I'm not sure how best to require this?

**Comment by tomvannuenen** [comment]
I just tried running `pd.read_pickle("../data/election2020_articles.pkl")` while running Pandas 2.0.3 which worked. Can you still reproduce the error @Emmavt?

**Comment by Emmavt** [comment]
Yes, with Pandas 2.1.2 it is still returning the same error.

**Comment by tomvannuenen** [comment]
Replaced Pickle with csv
