### ISSUE TITLE
API error with Tweepy using X (Twitter) Free Tier

### ISSUE THREAD

**Issue by aculich** [dlab-berkeley/Python-Web-APIs#5]
Warn people that to use most features of the the twitter API (e.g. what is in this notebook currently) they need to upgrade to a paid tier, as the free tier is very limited:

https://github.com/dlab-berkeley/Python-Web-APIs/blob/3923c1576085af5baded7722947c5d15784cfaae/lessons/03_twitter_api.ipynb#L25

And running code currently in this notebook from the free tier will yield an error like this:

```
TweepError: [{'message': 'You currently have access to a subset of Twitter API v2 endpoints and limited v1.1 endpoints (e.g. media post, oauth) only. If you need access to this endpoint, you may need a different access level. You can learn more here: https://developer.twitter.com/en/portal/product', 'code': 453}]
```

Which is [explained](https://twittercommunity.com/t/understanding-the-error-453-you-currently-have-access-to-a-subset-of-twitter-api-v2-endpoints/200361) on the X (twitter) developer forum as:

> [As announced previously 226](https://twittercommunity.com/t/deprecation-of-legacy-access-tiers-in-the-twitter-api/196162), we have deprecated our legacy Twitter API access tiers. By default, developers have access to the [Free tier](https://developer.twitter.com/en/portal/products/free) of the Twitter API.
> If you need access to other endpoints, you can sign up for either the [Basic](https://developer.twitter.com/en/portal/products/basic) or [Pro](https://developer.twitter.com/en/portal/products/pro) packages. These packages give developers access to a suite of v2 endpoints such as v2 search (in addition to the endpoints mentioned above) at different rate limits, read and post limits.

**Comment by tomvannuenen** [comment]
Removed the Twitter notebook for now. We should discuss which other API we want to demonstrate as their accessibility is becoming increasingly limited.
