### ISSUE TITLE
Provide more secure example of using and storing API credentials

### ISSUE THREAD

**Issue by aculich** [dlab-berkeley/Python-Web-APIs#6]
This should be replaced since it is an anti-pattern that we do not want to recommend in our workshops:

https://github.com/dlab-berkeley/Python-Web-APIs/blob/3923c1576085af5baded7722947c5d15784cfaae/lessons/02_api.ipynb#L67

While super convenient it almost always leads to someone accidentally checking in their credentials into github.

Instead, let's replace this with a re-useable pattern of [getpass](https://docs.python.org/3/library/getpass.html) and [configparser](https://pypi.org/project/configparser/) where the code will:

1. first try to obtain previously saved credentials by loading with configparser
2. then if not found, using getpass to request the credentials from the user (which works in notebooks as an input prompt)
3. then saves those user-inputted credentials using configparser to a path such as `~/.notebook-api-keys` which would be presumably outside of the .git controlled directory so it doesn't accidentally get added and checked in.

Note it will also be useful to mention the [The JupyterLab Credential Store](https://towardsdatascience.com/the-jupyterlab-credential-store-9cc3a0b9356), though since not everyone is using JupyterLab, we should have a more general solution available, as well, as noted above.

Here are some useful references:

- [Securely storing configuration credentials in a Jupyter Notebook](https://vickiboykis.com/2020/02/25/securely-storing-configuration-credentials-in-a-jupyter-notebook/) by Vicki Boykis
- [Keeping credentials safe in Jupyter Notebooks | by Alexandra Souly | Towards Data Science](https://towardsdatascience.com/keeping-credentials-safe-in-jupyter-notebooks-fbd215a8e311)
- [How do I properly protect my data access passwords (not jupyter tokens/passwords) on 3rd party jupyter hub services? - Special Topics / Security - Jupyter Community Forum](https://discourse.jupyter.org/t/how-do-i-properly-protect-my-data-access-passwords-not-jupyter-tokens-passwords-on-3rd-party-jupyter-hub-services/9277/2)
- [The JupyterLab Credential Store](https://towardsdatascience.com/the-jupyterlab-credential-store-9cc3a0b9356)

**Comment by tomvannuenen** [comment]
@aculich Great point, I just added this to the notebook and pushed to 
[secure_api](https://github.com/dlab-berkeley/Python-Web-APIs/tree/secure_api)
Can you have a look and check if this works on your end? If so, we can push to main.
