### ISSUE TITLE
01_api_lesson.md typos

### ISSUE THREAD

**Issue by Emmavt** [dlab-berkeley/Python-Web-APIs#9]
1. [Getting your API Keys](https://github.com/dlab-berkeley/Python-Web-APIs/blob/main/lessons/01_api_lesson.md#getting-your-api-keys) - item 5 of the list is missing
2. "Some basic terminology" section - very minor but we might want to remove the word basic in case people aren't familiar with them

**Comment by tomvannuenen** [comment]
fixed
